### ISSUE TITLE
add more notes

### ISSUE THREAD

**Issue by 0xmountaintop** [SebastianElvis/crypto-lecture-notes#1]
- https://intensecrypto.org/public/index.html
    + https://www.boazbarak.org/cs127spring16/
- https://github.com/cryptosubtlety/intuitive-advanced-cryptography
- https://github.com/crypto-cypher/privacy-for-identities/
- [Crypto 101](https://github.com/crypto101/book)
- [Practical-Cryptography-for-Developers-Book](https://github.com/nakov/Practical-Cryptography-for-Developers-Book)

**Comment by SebastianElvis** [comment]
Great. Can you propose a PR on these?

**Comment by 0xmountaintop** [comment]
for coding:

+ https://github.com/veorq/cryptocoding
+ https://bloodzer0.github.io/ossa/application-security/sdl/go-scp/
+ https://github.com/SalusaSecondus/CryptoGotchas

**Comment by 0xmountaintop** [comment]
> Great. Can you propose a PR on these?

I am not sure what should the structure be like.

Not all of them are course notes.

**Comment by SebastianElvis** [comment]
> for coding:
> 
> * [veorq/cryptocoding](https://github.com/veorq/cryptocoding)
> * [bloodzer0.github.io/ossa/application-security/sdl/go-scp](https://bloodzer0.github.io/ossa/application-security/sdl/go-scp/)
> * [SalusaSecondus/CryptoGotchas](https://github.com/SalusaSecondus/CryptoGotchas)

For this part, make a new section called `For coding`

**Comment by 0xmountaintop** [comment]
> > for coding:
> > 
> > * [veorq/cryptocoding](https://github.com/veorq/cryptocoding)
> > * [bloodzer0.github.io/ossa/application-security/sdl/go-scp](https://bloodzer0.github.io/ossa/application-security/sdl/go-scp/)
> > * [SalusaSecondus/CryptoGotchas](https://github.com/SalusaSecondus/CryptoGotchas)
> 
> For this part, make a new section called `For coding`

I see. Got it.

**Comment by SebastianElvis** [comment]
> * https://intensecrypto.org/public/index.html
>   

This should be in Misc

>   * https://www.boazbarak.org/cs127spring16/

This is in Course

> * https://github.com/cryptosubtlety/intuitive-advanced-cryptography
> * https://github.com/crypto-cypher/privacy-for-identities/
> * [Crypto 101](https://github.com/crypto101/book)
> * [Practical-Cryptography-for-Developers-Book](https://github.com/nakov/Practical-Cryptography-for-Developers-Book)

These are books

**Comment by SebastianElvis** [comment]
This issue has been addressed by PR #2. Thanks Haoyu!
